use_frameworks!
platform:ios,'8.0'
target "LianZhiParent" do
    pod 'FCFileManager'
    pod "FMDB"
pod 'YYKit'
pod 'SSZipArchive'
pod 'MJRefresh'
pod "FDFullscreenPopGesture"
pod 'Masonry'
pod 'SCRecorder'
pod 'ReactiveCocoa'
pod 'UMengAnalytics'
pod 'TTTAttributedLabel'
pod 'STPickerView'
pod 'CryptoSwift'
end
