pod "KRVideoPlayer"
pod "FCFileManager"
pod "FMDB"
pod "YYKit"
pod "SSZipArchive"
pod "MJRefresh"
pod "FDFullscreenPopGesture"
pod "Bugtags"
pod 'Masonry'
pod 'SCRecorder'
pod "ReactiveCocoa", "2.5"
pod 'UMengAnalytics'
