pod "KRVideoPlayer"
pod "FCFileManager"
pod "FMDB"
pod "YYKit"
pod "CTAssetsPickerController"
pod "SSZipArchive"
pod "MJRefresh"
pod 'SCRecorder'
pod "FDFullscreenPopGesture"
pod "Bugtags"
pod 'Masonry'
pod "ReactiveCocoa", "2.5"
pod 'SWTableViewCell', '~> 0.3.7'
pod "MWPhotoBrowser"
pod 'pop'
pod 'XHRealTimeBlur'
pod 'MGSwipeTableCell'
pod 'UMengAnalytics'
